// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:9aa217b0-ca42-4990-845a-56f9baca6d9c",
    "aws_cognito_region": "us-east-2",
    "aws_mobile_analytics_app_id": "f230d3f7d9de4f848fdd3bad074516a6",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://r4vi52ykl5dvzm24dl33lvqjta.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-hxfqmvi3uzag3e3vsp2mcanud4",
    "aws_content_delivery_bucket": "mashcores-20181214222812-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://mashcores-20181214222812-hostingbucket.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
